<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iaBZje7' shared service.

return $this->privates['.service_locator.iaBZje7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AuthentificationController::index' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::addadmin' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::adduser' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::admin' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::ajout' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::argent' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::caissier' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\ServiceController::systeme' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::usercompte' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\AuthentificationController:index' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:addadmin' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:adduser' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:admin' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:ajout' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:argent' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:caissier' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\ServiceController:systeme' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:usercompte' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\AuthentificationController::index' => '?',
    'App\\Controller\\ServiceController::addadmin' => '?',
    'App\\Controller\\ServiceController::adduser' => '?',
    'App\\Controller\\ServiceController::admin' => '?',
    'App\\Controller\\ServiceController::ajout' => '?',
    'App\\Controller\\ServiceController::argent' => '?',
    'App\\Controller\\ServiceController::caissier' => '?',
    'App\\Controller\\ServiceController::register' => '?',
    'App\\Controller\\ServiceController::systeme' => '?',
    'App\\Controller\\ServiceController::usercompte' => '?',
    'App\\Controller\\AuthentificationController:index' => '?',
    'App\\Controller\\ServiceController:addadmin' => '?',
    'App\\Controller\\ServiceController:adduser' => '?',
    'App\\Controller\\ServiceController:admin' => '?',
    'App\\Controller\\ServiceController:ajout' => '?',
    'App\\Controller\\ServiceController:argent' => '?',
    'App\\Controller\\ServiceController:caissier' => '?',
    'App\\Controller\\ServiceController:register' => '?',
    'App\\Controller\\ServiceController:systeme' => '?',
    'App\\Controller\\ServiceController:usercompte' => '?',
]);
