<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yLBQTW1' shared service.

return $this->privates['.service_locator.yLBQTW1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'JWTEncoder' => ['services', 'lexik_jwt_authentication.encoder', 'getLexikJwtAuthentication_EncoderService.php', true],
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
], [
    'JWTEncoder' => '?',
    'passwordEncoder' => '?',
]);
