<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVsEXQI6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVsEXQI6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVsEXQI6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVsEXQI6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVsEXQI6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VsEXQI6',
    'container.build_id' => '9ca857b4',
    'container.build_time' => 1566204325,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVsEXQI6');
