<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLJ7PPEx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLJ7PPEx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLJ7PPEx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLJ7PPEx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLJ7PPEx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LJ7PPEx',
    'container.build_id' => '1cde4c9e',
    'container.build_time' => 1565980756,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLJ7PPEx');
