<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXIr8Ox1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXIr8Ox1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXIr8Ox1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXIr8Ox1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXIr8Ox1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XIr8Ox1',
    'container.build_id' => 'b5ad1057',
    'container.build_time' => 1566073811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXIr8Ox1');
